sudo: required
language: generic

services:
  - docker

#Note that we use dev dockerfile only beaucse it has access to the test as well
before_install:
  - docker build -t gargvatsal2000/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gargvatsal2000/react-test npm test -- --coverage

#Build prod version of all our projects and push them off to dockerHub
#Dont specift the dockerfile, it will use the default one onlt
after_success:
  - docker build -t gargvatsal2000/multi-client ./client
  - docker build -t gargvatsal2000/multi-nginx ./nginx
  - docker build -t gargvatsal2000/multi-server ./server
  - docker build -t gargvatsal2000/multi-worker ./worker
  #Push all the built prod files to dockerhub
  # Log in to the docker CLI, Id and pass set in the travis site
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gargvatsal2000/multi-client
  - docker push gargvatsal2000/multi-nginx
  - docker push gargvatsal2000/multi-server
  - docker push gargvatsal2000/multi-worker
